version: '3.8'
services:

  # MySQL
  mysql:
    profiles: ["all", "mysql"]
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: ${mysql_database_name}
      MYSQL_ROOT_PASSWORD: ${mysql_database_password}
    ports:
      - "${mysql_port}:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.env:/.env
  
  # PostgreSQL.
  postgres:
    profiles: ["all", "postgres"]
    image: postgres:13.3-alpine
    ports:
      - "${postgres_port}:5432"
    environment:  # https://github.com/docker-library/docs/tree/master/postgres#environment-variables
      - POSTGRES_USER=${postgres_admin_user}
      - POSTGRES_PASSWORD=${postgres_admin_password}
      - POSTGRES_DB=${postgres_database_name}
    volumes:
      - ./.env:/.env
      - postgres-volume:/var/lib/postgresql/data
  
  #MongoDB
  mongodb:
    profiles: ["all", "mongodb"]
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  mysql-db:
    driver: local
  postgres-volume:
    external: false
  dbdata6: