version: '3.8'
services:
  mysql:
    profiles: ["all", "database", "mysql"]
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: ${mysql_database_name}
      MYSQL_ROOT_PASSWORD: ${mysql_database_password}
    ports:
      - "${mysql_port}:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.env:/.env
volumes:
  mysql-db:
    driver: local